# See Requirements for recommended tool versions.

# Building/installing  SDL out-of-tree makes for a less noisy "git status"
SDL_BUILD=$(PWD)/3rd_party/SDL/build
SDL_INSTALL=$(PWD)/3rd_party/SDL

# Location of the sdl2-config program that tells other targets
# where to find SDL libraries and headers.  If you want to use
# a local version of SDL, change this line.
SDL_CONFIG=$(SDL_INSTALL)/bin/sdl2-config

# Flags for nanopond generated by sdl2-config
SDL_CFLAGS=`$(SDL_CONFIG) --cflags`
SDL_LIB=`$(SDL_CONFIG) --libs`

# Only useful in np-t and np-xt targets
NUM_THREADS=32

CFLAGS=-Ofast -Wall -Wextra -Werror -g -std=c2x
CDEBUG_FLAGS=-Og -Wall -Wextra -Werror -g \
			 -std=c2x -fsanitize=address -fsanitize=leak

# Use this to build everything.
all: np-all
clean: np-clean sdl-clean

# nanopond targets:  x=Use SDL for GUI, t=multithreaded using pthreads
np-all: np np-x np-t np-xt np-dbg

np: nanopond.c
	gcc $(CFLAGS) -o np nanopond.c

np-dbg: nanopond.c
	gcc $(CDEBUG_FLAGS) -o np-dbg nanopond.c

np-x: sdl-install nanopond.c
	gcc -DUSE_SDL $(SDL_CFLAGS) \
		$(CFLAGS) -o np-x nanopond.c $(SDL_LIB)

np-t: nanopond.c
	gcc -DUSE_PTHREAD_COUNT=$(NUM_THREADS) \
		$(CFLAGS) -o np-t nanopond.c -lpthread

np-xt: sdl-install nanopond.c
	gcc -DUSE_SDL -DUSE_PTHREAD_COUNT=$(NUM_THREADS) $(SDL_CFLAGS) \
		$(CFLAGS) -o np-xt nanopond.c $(SDL_LIB) -lpthread

np-clean:
	rm -rf *.o np np-t np-x np-xt np-dbg np.13.test *.dSYM

# re-run after changing the underlying algorithm
np-gold: np
	./np -s 13 | head -n 100 > np.13.gold

# re-run prior to any commit.
np-test:
	./np -s 13 | head -n 100 > np.13.test
	diff -u np.13.gold np.13.test

# sdl targets
sdl-init:
	git submodule init
	git submodule update

sdl-install: sdl-init
	cmake -S ./SDL -B $(SDL_BUILD)
	cmake --build $(SDL_BUILD) -j
	cmake --install $(SDL_BUILD) --prefix=$(SDL_INSTALL)

sdl-clean:
	rm -rf ./3rd_party


